types = {
    1: 'Normal',
    2: 'Fire',
    3: 'Water',
    4: 'Grass',
    5: 'Flying',
    6: 'Fighting',
    7: 'Poison',
    8: 'Eletric',
    9: 'Ground',
    10: 'Rock',
    11: 'Psychic',
    12: 'Ice',
    13: 'Bug',
    14: 'Ghost',
    15: 'Steel',
    16: 'Dragon',
    17: 'Dark',
    18: 'Fairy',
}